// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhNai6s12W-ps4mQLEQ-pg4xVknNwtyR8',
    appId: '1:827133554416:web:375a1842cbeec6304d9c35',
    messagingSenderId: '827133554416',
    projectId: 'attendify-app-fb742',
    authDomain: 'attendify-app-fb742.firebaseapp.com',
    storageBucket: 'attendify-app-fb742.firebasestorage.app',
    measurementId: 'G-S918VTF2L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVPPZxkHYlHCTRoCh1hG4ZdSAuqbbLNQ',
    appId: '1:827133554416:android:7ff9fcea699e61134d9c35',
    messagingSenderId: '827133554416',
    projectId: 'attendify-app-fb742',
    storageBucket: 'attendify-app-fb742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTbDqSwAjCtLB4HJqYeWMSl15tAvzzFyM',
    appId: '1:827133554416:ios:97bb5522891859814d9c35',
    messagingSenderId: '827133554416',
    projectId: 'attendify-app-fb742',
    storageBucket: 'attendify-app-fb742.firebasestorage.app',
    iosClientId: '827133554416-82hetrv8osje1o1k0f7cbrie3bs7ptiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTbDqSwAjCtLB4HJqYeWMSl15tAvzzFyM',
    appId: '1:827133554416:ios:97bb5522891859814d9c35',
    messagingSenderId: '827133554416',
    projectId: 'attendify-app-fb742',
    storageBucket: 'attendify-app-fb742.firebasestorage.app',
    iosClientId: '827133554416-82hetrv8osje1o1k0f7cbrie3bs7ptiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhNai6s12W-ps4mQLEQ-pg4xVknNwtyR8',
    appId: '1:827133554416:web:74d071c8d12696c74d9c35',
    messagingSenderId: '827133554416',
    projectId: 'attendify-app-fb742',
    authDomain: 'attendify-app-fb742.firebaseapp.com',
    storageBucket: 'attendify-app-fb742.firebasestorage.app',
    measurementId: 'G-W4HT946K58',
  );

}